name: Deploy to GitHub Pages

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Deploy
        run: |
          # Здесь можно добавить команды для сборки Вашего приложения
          echo "Deploying to GitHub Pages"
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Deploying version ${{ github.event.release.tag }}"
          git push origin gh-pages
